import type { NextPage } from 'next'
import Head from 'next/head'
import ProgressStrip from '../components/ProgressStrip'
import Form from '../components/Form'
import { useState } from 'react'
import styles from '../styles/index.module.scss'
import Review from '../components/Review'
import QuoteInfo from '../types/QuoteInfo'
import Payment from '../components/Payment'
import LoadingOverlay from '../components/LoadingOverlay'

const GetQuote: NextPage = () => {
  const [progressStripIdx, setProgressStripIdx] = useState(0)
  const [loadingContent, setLoadingContent] = useState(false)
  const [quoteInfo, setQuoteInfo] = useState<QuoteInfo>()

  function reviewQuote(body: QuoteInfo) {
    setQuoteInfo(body)
    setProgressStripIdx(1)
  }

  function proceedToPayment() {
    setProgressStripIdx(2)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Get a Quote</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ProgressStrip idx={progressStripIdx}/>
        { progressStripIdx === 0 && <Form reviewQuote={reviewQuote} setLoadingContent={setLoadingContent} /> }
        { progressStripIdx === 1 && <Review quoteInfo={quoteInfo!} proceedToPayment={proceedToPayment} /> }
        { progressStripIdx === 2 && <Payment /> }
      </main>

      { loadingContent && <LoadingOverlay /> }
    </div>
  )
}

export default GetQuote
