import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/MyInsurance.module.scss'
import Quote from '../types/Quote'
import Contract from '../types/Contract'

const MyInsurance: NextPage = () => {
  const [userId, setUserId] = useState(-1)
  const [quotes, setQuotes] = useState<Quote[]>()
  const [contracts, setContracts] = useState<Contract[]>()

  useEffect(() => {
    async function fetchData() {
      const userIdFromStorage = parseInt(localStorage.getItem('userId')!)
      setUserId(userIdFromStorage)
      const quotesRes = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/quotes/${userIdFromStorage}`, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      })
      setQuotes(await quotesRes.json())
      const contractsRes = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/contracts/${userIdFromStorage}`, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      })
      setContracts(await contractsRes.json())
    }
    if (userId === -1) fetchData()
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>My Insurance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.card}>
          <header className={styles.header}>
            <h1>My Insurance</h1>
          </header>
          <div className={styles.contentContainer}>
            <div className={styles.description}>
              Previous Quotes
            </div>
            <div className={styles.quoteValue}>
              {quotes && quotes.map(quote =>
                <div key={quote.quote_id} >{ new Intl.NumberFormat('ja-JP', { style: 'currency', currency: 'JPY' }).format(quote.quote_value) }</div>
              )}
            </div>
          </div>
        </div>

        <div className={styles.card}>
          <header className={styles.header}>
            <h1>My Contracts</h1>
          </header>
          <div className={styles.contentContainer}>
            <div className={styles.description}>
              Contracts for User { userId }
            </div>
            <div className={styles.contractNameContainer}>
              {contracts && contracts.map(contract =>
                <div className={styles.contractName} key={contract.contract_id} >{contract.company_name}</div>
              )}
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

export default MyInsurance
